name: FORK-TO-BRANCH

on:
  workflow_dispatch:
    inputs:
      source-branch:
        type: string
        description: The name of the branch from forked-repo.
        required: true
      contributor-name:
        type: string
        description: write your github-user name.
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0 
            
      - name: Check branch exist
        run: |
          set +e
          cmd="$(git rev-parse --verify --quiet  feature/${{ github.event.inputs.source-branch }})"
          if [[ ! -z "$cmd" ]]
          then
            git branch -d feature/${{ github.event.inputs.source-branch }}
          fi 

#       - name: Git clone forked pipeline
#         run: |
#           pwd
#           git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.inputs.contributor-name }}/fork-to-branch.git
#           ls -l
          
#       - name: Git checkout origin branch
#         working-directory: fork-to-branch
#         run: |
#           ls -l
#           pwd
#           git checkout origin/${{ github.event.inputs.source-branch }}
      
      - name: Git remote add upstream
        run: |
          git remote add upstream https://github.com/${{ github.event.inputs.contributor-name }}/fork-to-branch.git
          git fetch --all
          git checkout upstream/${{ github.event.inputs.source-branch }}
          git checkout -b feature/${{ github.event.inputs.source-branch }}
          git push --set-upstream origin feature/${{ github.event.inputs.source-branch }}
          

          
          echo "Forked branch ${{ github.event.inputs.source-branch }} has been pushed to fork-to-branch repo feature/${{ github.event.inputs.source-branch }}"

#          git checkout -b feature/${{ github.event.inputs.source-branch }}
#          git push

      
#       - name: Git create new branch
#         working-directory: fork-to-branch
#         run: git checkout -b feature/${{ github.event.inputs.source-branch }}
      
#       - name: Git push new branch
#         working-directory: fork-to-branch
#         run: git push --set-upstream origin feature/${{ github.event.inputs.source-branch }}














