name: FORK-TO-BRANCH

on:
#   workflow_dispatch:
#     inputs:
#       source-branch:
#         type: string
#         description: The name of the branch from forked-repo.
#         required: true
#       contributor-name:
#         type: string
#         description: write your github-user name.
#         required: true
  issue_comment:
    types: [created]
  pull_request:
    types: [created, synchronize, reopened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      HEAD_OWNER: ${{ github.event.issue.pull_request.head.repo.owner.login }}
    steps: 
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0 
            token: ${{ secrets.PERSONAL_TOKEN }}
            
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "run branch"
  
      - name: Check if branch exists
        if: steps.check.outputs.triggered == 'true'
        run: |
          existed_in_repo=$(git ls-remote --heads origin pr/${{ github.event.issue.pull_request.head.ref }})
          if [[ -z ${existed_in_repo} ]]
          then
            echo "branch pr/${{ github.event.issue.pull_request.head.ref }} is not exists"
          else
           echo "branch pr/${{ github.event.issue.pull_request.head.ref }} deleted" 
          fi


#       - name: Git remote add upstream
#         if: steps.check.outputs.triggered == 'true'
#         run: |
#           git remote add upstream https://github.com/${{ env.HEAD_OWNER }}/fork-to-branch.git
#           git fetch --all
#           git checkout upstream/${{ github.event.pull_request.head.ref }}
#           git checkout -b pr/${{ github.event.pull_request.head.ref }}
#           git push --set-upstream origin pr/${{ github.event.pull_request.head.ref }}
          
#           echo "Forked branch ${{ github.event.pull_request.head.ref }} has been pushed to fork-to-branch repo pr/${{ github.event.pull_request.head.ref }}"















